name: My Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Verify code style
        run: gradle checkstyleMain

      - name: Build with Gradle
        run: gradle build

      - name: Publish JAR
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p release
          cp build/libs/*.jar release/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-pipeline